-- ============================================================================
--  RECEPTION SALFA — Migration « ARTICLES UNIFIÉS » (LABO + ECHO)
-- ============================================================================
--  Objectif : mettre une base locale EXISTANTE en conformité avec la logique
--  des articles unifiés :
--    • Laboratoire (famille LABO) : tous les examens (NFS, Glycémie, Créatinine,
--      CRP, Groupe Sanguin, ECBU, Goutte épaisse, TP/INR, bilans complets, etc.)
--      ET les consommables (Tube EDTA, Réactif Glycémie, Lames porte-objet)
--      sont intégrés dans la table unifiée `articles`.
--    • Échographie (famille ECHO) : tous les actes (Abdominale, Pelvienne,
--      Obstétricale, Cardiaque, Rénale, Thyroïdienne, Mammaire, Doppler,
--      Prostatique, etc.) ET le gel d'échographie sont intégrés dans `articles`.
--    • Modules synchronisés : Magasinier, Laboratoire, Médecin, Caisse et
--      Facturation exploitent ce référentiel unifié.
--
--  Mode d'emploi :
--    1. Faites une sauvegarde de la base (Export phpMyAdmin / mysqldump).
--    2. Importez ce fichier dans phpMyAdmin (base `reception_salfa`).
--    3. Rouvrez l'application : au démarrage, elle réaligne automatiquement
--       le miroir `catalogue_laboratoire` sur la table `articles` et intègre
--       les examens personnalisés de l'ancien catalogue dans `articles`.
--
--  Sécurité : toutes les insertions sont idempotentes (INSERT IGNORE par
--  identifiant). AUCUN article existant n'est modifié ni écrasé ; les données
--  métier (patients, ventes, factures…) ne sont pas touchées.
-- ============================================================================

USE `reception_salfa`;

-- ----------------------------------------------------------------------------
--  BASE UNIFIÉE DES ARTICLES — familles LABO (examens + consommables) et ECHO
--  (actes + gel). Logique « articles unifiés » : Magasinier, Laboratoire,
--  Médecin, Caisse et Facturation exploitent la table articles comme
--  référentiel unique. Insertions idempotentes par identifiant (INSERT IGNORE) :
--  aucun article existant n est écrasé, les données déjà en base sont conservées.
-- ----------------------------------------------------------------------------
INSERT IGNORE INTO `articles`
(`id`, `name`, `family`, `unit`, `barcode`, `prix_achat`, `prix_comptoir`, `prix_societe`, `prix_externe`, `stock_central`, `stock_pharmacie`, `data_json`)
VALUES
('exam-001', 'NFS (Numération Formule Sanguine)', 'LABO', 'analyse', 'LAB001', 0, 15000, 13000, 18000, 0, 0, '{"id":"exam-001","name":"NFS (Numération Formule Sanguine)","code":"LAB001","family":"LABO","unit":"analyse","barcode":"LAB001","priceComptoir":15000,"priceSociete":13000,"priceExterne":18000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"hematologie","parameters":["Globules Rouges","Globules Blancs","Hémoglobine","Plaquettes","Hématocrite"],"sampleType":"Sang veineux (EDTA)","urgentPrice":25000,"durationHours":4}'),
('exam-002', 'Glycémie à jeun', 'LABO', 'analyse', 'LAB002', 0, 8000, 7000, 10000, 0, 0, '{"id":"exam-002","name":"Glycémie à jeun","code":"LAB002","family":"LABO","unit":"analyse","barcode":"LAB002","priceComptoir":8000,"priceSociete":7000,"priceExterne":10000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"biochimie","parameters":["Glucose"],"sampleType":"Sang veineux","urgentPrice":15000,"durationHours":1}'),
('exam-003', 'Créatinine', 'LABO', 'analyse', 'LAB003', 0, 10000, 9000, 12000, 0, 0, '{"id":"exam-003","name":"Créatinine","code":"LAB003","family":"LABO","unit":"analyse","barcode":"LAB003","priceComptoir":10000,"priceSociete":9000,"priceExterne":12000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"biochimie","parameters":["Créatinine"],"sampleType":"Sang veineux","urgentPrice":18000,"durationHours":2}'),
('exam-004', 'CRP (Protéine C-Réactive)', 'LABO', 'analyse', 'LAB004', 0, 7000, 6000, 9000, 0, 0, '{"id":"exam-004","name":"CRP (Protéine C-Réactive)","code":"LAB004","family":"LABO","unit":"analyse","barcode":"LAB004","priceComptoir":7000,"priceSociete":6000,"priceExterne":9000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"biochimie","parameters":["CRP"],"sampleType":"Sang veineux","urgentPrice":12000,"durationHours":1}'),
('exam-005', 'Groupe Sanguin & Rhésus', 'LABO', 'analyse', 'LAB005', 0, 10000, 9000, 12000, 0, 0, '{"id":"exam-005","name":"Groupe Sanguin & Rhésus","code":"LAB005","family":"LABO","unit":"analyse","barcode":"LAB005","priceComptoir":10000,"priceSociete":9000,"priceExterne":12000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"hematologie","parameters":["Groupe ABO","Rhésus"],"sampleType":"Sang veineux","urgentPrice":15000,"durationHours":2}'),
('exam-006', 'ECBU (Culture + Antibiogramme)', 'LABO', 'analyse', 'LAB006', 0, 15000, 13000, 18000, 0, 0, '{"id":"exam-006","name":"ECBU (Culture + Antibiogramme)","code":"LAB006","family":"LABO","unit":"analyse","barcode":"LAB006","priceComptoir":15000,"priceSociete":13000,"priceExterne":18000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"bacteriologie","parameters":["Culture","Antibiogramme"],"sampleType":"Urine (pot stérile)","urgentPrice":25000,"durationHours":48}'),
('exam-007', 'Goutte épaisse (Plasmodium)', 'LABO', 'analyse', 'LAB007', 0, 10000, 9000, 12000, 0, 0, '{"id":"exam-007","name":"Goutte épaisse (Plasmodium)","code":"LAB007","family":"LABO","unit":"analyse","barcode":"LAB007","priceComptoir":10000,"priceSociete":9000,"priceExterne":12000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"parasitologie","parameters":["Plasmodium"],"sampleType":"Sang veineux","urgentPrice":18000,"durationHours":4}'),
('exam-008', 'TP / INR', 'LABO', 'analyse', 'LAB008', 0, 12000, 11000, 15000, 0, 0, '{"id":"exam-008","name":"TP / INR","code":"LAB008","family":"LABO","unit":"analyse","barcode":"LAB008","priceComptoir":12000,"priceSociete":11000,"priceExterne":15000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"hemostase","parameters":["TP","INR"],"sampleType":"Sang veineux (citraté)","urgentPrice":20000,"durationHours":2}'),
('exam-009', 'Bilan lipidique complet', 'LABO', 'analyse', 'LAB009', 0, 20000, 18000, 25000, 0, 0, '{"id":"exam-009","name":"Bilan lipidique complet","code":"LAB009","family":"LABO","unit":"analyse","barcode":"LAB009","priceComptoir":20000,"priceSociete":18000,"priceExterne":25000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"biochimie","parameters":["Cholestérol Total","HDL","LDL","Triglycérides"],"sampleType":"Sang veineux","urgentPrice":30000,"durationHours":2}'),
('exam-010', 'Bilan hépatique complet', 'LABO', 'analyse', 'LAB010', 0, 22000, 20000, 28000, 0, 0, '{"id":"exam-010","name":"Bilan hépatique complet","code":"LAB010","family":"LABO","unit":"analyse","barcode":"LAB010","priceComptoir":22000,"priceSociete":20000,"priceExterne":28000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"biochimie","parameters":["ASAT","ALAT","GGT","Bilirubine"],"sampleType":"Sang veineux","urgentPrice":35000,"durationHours":2}'),
('exam-011', 'Bilan rénal complet', 'LABO', 'analyse', 'LAB011', 0, 18000, 16000, 22000, 0, 0, '{"id":"exam-011","name":"Bilan rénal complet","code":"LAB011","family":"LABO","unit":"analyse","barcode":"LAB011","priceComptoir":18000,"priceSociete":16000,"priceExterne":22000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"biochimie","parameters":["Créatinine","Urée","Acide Urique"],"sampleType":"Sang veineux","urgentPrice":28000,"durationHours":2}'),
('exam-012', 'Ionogramme sanguin', 'LABO', 'analyse', 'LAB012', 0, 15000, 13000, 18000, 0, 0, '{"id":"exam-012","name":"Ionogramme sanguin","code":"LAB012","family":"LABO","unit":"analyse","barcode":"LAB012","priceComptoir":15000,"priceSociete":13000,"priceExterne":18000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"biochimie","parameters":["Sodium","Potassium","Chlore"],"sampleType":"Sang veineux","urgentPrice":22000,"durationHours":2}'),
('exam-013', 'TDR Paludisme', 'LABO', 'analyse', 'LAB013', 0, 5000, 4500, 6000, 0, 0, '{"id":"exam-013","name":"TDR Paludisme","code":"LAB013","family":"LABO","unit":"analyse","barcode":"LAB013","priceComptoir":5000,"priceSociete":4500,"priceExterne":6000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"parasitologie","parameters":["TDR Paludisme"],"sampleType":"Sang capillaire","urgentPrice":8000,"durationHours":1}'),
('exam-014', 'Sérologie VIH / Syphilis', 'LABO', 'analyse', 'LAB014', 0, 12000, 10000, 15000, 0, 0, '{"id":"exam-014","name":"Sérologie VIH / Syphilis","code":"LAB014","family":"LABO","unit":"analyse","barcode":"LAB014","priceComptoir":12000,"priceSociete":10000,"priceExterne":15000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true,"category":"serologie","parameters":["VIH 1/2","TPHA/VDRL"],"sampleType":"Sang veineux","urgentPrice":20000,"durationHours":2}'),
('art-006', 'Tube EDTA', 'LABO', 'unité', '619100000006', 100, 300, 250, 400, 200, 50, '{"id":"art-006","name":"Tube EDTA","family":"LABO","unit":"unité","barcode":"619100000006","priceComptoir":300,"priceSociete":250,"priceExterne":400,"purchasePrice":100,"stockCentral":200,"stockPharmacie":50,"minStockCentral":30,"minStockPharmacie":20}'),
('art-007', 'Réactif Glycémie', 'LABO', 'flacon', '619100000007', 2500, 5000, 4500, 6000, 30, 10, '{"id":"art-007","name":"Réactif Glycémie","family":"LABO","unit":"flacon","barcode":"619100000007","priceComptoir":5000,"priceSociete":4500,"priceExterne":6000,"purchasePrice":2500,"stockCentral":30,"stockPharmacie":10,"minStockCentral":5,"minStockPharmacie":3,"supplier":"DISPHAR LABO","expiryDate":"2027-03-31"}'),
('art-lab-015', 'Lames porte-objet', 'LABO', 'boîte', '619100000015', 4000, 8000, 7000, 10000, 50, 15, '{"id":"art-lab-015","name":"Lames porte-objet","family":"LABO","unit":"boîte","barcode":"619100000015","priceComptoir":8000,"priceSociete":7000,"priceExterne":10000,"purchasePrice":4000,"stockCentral":50,"stockPharmacie":15,"minStockCentral":10,"minStockPharmacie":5}'),
('echo-abd', 'Échographie abdominale', 'ECHO', 'acte', 'ECH001', 0, 25000, 22000, 30000, 0, 0, '{"id":"echo-abd","name":"Échographie abdominale","code":"ECH001","family":"ECHO","unit":"acte","barcode":"ECH001","priceComptoir":25000,"priceSociete":22000,"priceExterne":30000,"urgentPrice":35000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true}'),
('echo-pel', 'Échographie pelvienne', 'ECHO', 'acte', 'ECH002', 0, 25000, 22000, 30000, 0, 0, '{"id":"echo-pel","name":"Échographie pelvienne","code":"ECH002","family":"ECHO","unit":"acte","barcode":"ECH002","priceComptoir":25000,"priceSociete":22000,"priceExterne":30000,"urgentPrice":35000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true}'),
('echo-obs', 'Échographie obstétricale', 'ECHO', 'acte', 'ECH003', 0, 25000, 22000, 30000, 0, 0, '{"id":"echo-obs","name":"Échographie obstétricale","code":"ECH003","family":"ECHO","unit":"acte","barcode":"ECH003","priceComptoir":25000,"priceSociete":22000,"priceExterne":30000,"urgentPrice":35000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true}'),
('echo-car', 'Échographie cardiaque (ETT)', 'ECHO', 'acte', 'ECH004', 0, 40000, 35000, 45000, 0, 0, '{"id":"echo-car","name":"Échographie cardiaque (ETT)","code":"ECH004","family":"ECHO","unit":"acte","barcode":"ECH004","priceComptoir":40000,"priceSociete":35000,"priceExterne":45000,"urgentPrice":50000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true}'),
('echo-ren', 'Échographie rénale', 'ECHO', 'acte', 'ECH005', 0, 25000, 22000, 30000, 0, 0, '{"id":"echo-ren","name":"Échographie rénale","code":"ECH005","family":"ECHO","unit":"acte","barcode":"ECH005","priceComptoir":25000,"priceSociete":22000,"priceExterne":30000,"urgentPrice":35000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true}'),
('echo-thy', 'Échographie thyroïdienne', 'ECHO', 'acte', 'ECH006', 0, 25000, 22000, 30000, 0, 0, '{"id":"echo-thy","name":"Échographie thyroïdienne","code":"ECH006","family":"ECHO","unit":"acte","barcode":"ECH006","priceComptoir":25000,"priceSociete":22000,"priceExterne":30000,"urgentPrice":35000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true}'),
('echo-mam', 'Échographie mammaire', 'ECHO', 'acte', 'ECH007', 0, 25000, 22000, 30000, 0, 0, '{"id":"echo-mam","name":"Échographie mammaire","code":"ECH007","family":"ECHO","unit":"acte","barcode":"ECH007","priceComptoir":25000,"priceSociete":22000,"priceExterne":30000,"urgentPrice":35000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true}'),
('echo-pmo', 'Échographie des parties molles', 'ECHO', 'acte', 'ECH008', 0, 25000, 22000, 30000, 0, 0, '{"id":"echo-pmo","name":"Échographie des parties molles","code":"ECH008","family":"ECHO","unit":"acte","barcode":"ECH008","priceComptoir":25000,"priceSociete":22000,"priceExterne":30000,"urgentPrice":35000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true}'),
('echo-dop', 'Échographie Doppler', 'ECHO', 'acte', 'ECH009', 0, 35000, 30000, 40000, 0, 0, '{"id":"echo-dop","name":"Échographie Doppler","code":"ECH009","family":"ECHO","unit":"acte","barcode":"ECH009","priceComptoir":35000,"priceSociete":30000,"priceExterne":40000,"urgentPrice":45000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true}'),
('echo-pro', 'Échographie prostatique', 'ECHO', 'acte', 'ECH010', 0, 25000, 22000, 30000, 0, 0, '{"id":"echo-pro","name":"Échographie prostatique","code":"ECH010","family":"ECHO","unit":"acte","barcode":"ECH010","priceComptoir":25000,"priceSociete":22000,"priceExterne":30000,"urgentPrice":35000,"purchasePrice":0,"stockCentral":0,"stockPharmacie":0,"minStockCentral":0,"minStockPharmacie":0,"alertDisabledCentral":true,"alertDisabledPharmacie":true}'),
('art-008', 'Gel échographie', 'ECHO', 'flacon', '619100000008', 2000, 5000, 4000, 6000, 0, 4, '{"id":"art-008","name":"Gel échographie","family":"ECHO","unit":"flacon","barcode":"619100000008","priceComptoir":5000,"priceSociete":4000,"priceExterne":6000,"purchasePrice":2000,"stockCentral":0,"stockPharmacie":4,"minStockCentral":5,"minStockPharmacie":2}');

-- ----------------------------------------------------------------------------
--  Miroir de compatibilité : catalogue_laboratoire (14 examens standards).
--  La table articles reste la source de vérité ; ce miroir est réaligné à
--  chaque démarrage de l application. Insertions idempotentes (INSERT IGNORE).
-- ----------------------------------------------------------------------------
INSERT IGNORE INTO `catalogue_laboratoire` (`id`, `code`, `name`, `category`, `data_json`)
VALUES
('exam-001', 'LAB001', 'NFS (Numération Formule Sanguine)', 'hematologie', '{"id":"exam-001","code":"LAB001","name":"NFS (Numération Formule Sanguine)","category":"hematologie","parameters":["Globules Rouges","Globules Blancs","Hémoglobine","Plaquettes","Hématocrite"],"sampleType":"Sang veineux (EDTA)","priceComptoir":15000,"priceSociete":13000,"priceExterne":18000,"urgentPrice":25000,"durationHours":4}'),
('exam-002', 'LAB002', 'Glycémie à jeun', 'biochimie', '{"id":"exam-002","code":"LAB002","name":"Glycémie à jeun","category":"biochimie","parameters":["Glucose"],"sampleType":"Sang veineux","priceComptoir":8000,"priceSociete":7000,"priceExterne":10000,"urgentPrice":15000,"durationHours":1}'),
('exam-003', 'LAB003', 'Créatinine', 'biochimie', '{"id":"exam-003","code":"LAB003","name":"Créatinine","category":"biochimie","parameters":["Créatinine"],"sampleType":"Sang veineux","priceComptoir":10000,"priceSociete":9000,"priceExterne":12000,"urgentPrice":18000,"durationHours":2}'),
('exam-004', 'LAB004', 'CRP (Protéine C-Réactive)', 'biochimie', '{"id":"exam-004","code":"LAB004","name":"CRP (Protéine C-Réactive)","category":"biochimie","parameters":["CRP"],"sampleType":"Sang veineux","priceComptoir":7000,"priceSociete":6000,"priceExterne":9000,"urgentPrice":12000,"durationHours":1}'),
('exam-005', 'LAB005', 'Groupe Sanguin & Rhésus', 'hematologie', '{"id":"exam-005","code":"LAB005","name":"Groupe Sanguin & Rhésus","category":"hematologie","parameters":["Groupe ABO","Rhésus"],"sampleType":"Sang veineux","priceComptoir":10000,"priceSociete":9000,"priceExterne":12000,"urgentPrice":15000,"durationHours":2}'),
('exam-006', 'LAB006', 'ECBU (Culture + Antibiogramme)', 'bacteriologie', '{"id":"exam-006","code":"LAB006","name":"ECBU (Culture + Antibiogramme)","category":"bacteriologie","parameters":["Culture","Antibiogramme"],"sampleType":"Urine (pot stérile)","priceComptoir":15000,"priceSociete":13000,"priceExterne":18000,"urgentPrice":25000,"durationHours":48}'),
('exam-007', 'LAB007', 'Goutte épaisse (Plasmodium)', 'parasitologie', '{"id":"exam-007","code":"LAB007","name":"Goutte épaisse (Plasmodium)","category":"parasitologie","parameters":["Plasmodium"],"sampleType":"Sang veineux","priceComptoir":10000,"priceSociete":9000,"priceExterne":12000,"urgentPrice":18000,"durationHours":4}'),
('exam-008', 'LAB008', 'TP / INR', 'hemostase', '{"id":"exam-008","code":"LAB008","name":"TP / INR","category":"hemostase","parameters":["TP","INR"],"sampleType":"Sang veineux (citraté)","priceComptoir":12000,"priceSociete":11000,"priceExterne":15000,"urgentPrice":20000,"durationHours":2}'),
('exam-009', 'LAB009', 'Bilan lipidique complet', 'biochimie', '{"id":"exam-009","code":"LAB009","name":"Bilan lipidique complet","category":"biochimie","parameters":["Cholestérol Total","HDL","LDL","Triglycérides"],"sampleType":"Sang veineux","priceComptoir":20000,"priceSociete":18000,"priceExterne":25000,"urgentPrice":30000,"durationHours":2}'),
('exam-010', 'LAB010', 'Bilan hépatique complet', 'biochimie', '{"id":"exam-010","code":"LAB010","name":"Bilan hépatique complet","category":"biochimie","parameters":["ASAT","ALAT","GGT","Bilirubine"],"sampleType":"Sang veineux","priceComptoir":22000,"priceSociete":20000,"priceExterne":28000,"urgentPrice":35000,"durationHours":2}'),
('exam-011', 'LAB011', 'Bilan rénal complet', 'biochimie', '{"id":"exam-011","code":"LAB011","name":"Bilan rénal complet","category":"biochimie","parameters":["Créatinine","Urée","Acide Urique"],"sampleType":"Sang veineux","priceComptoir":18000,"priceSociete":16000,"priceExterne":22000,"urgentPrice":28000,"durationHours":2}'),
('exam-012', 'LAB012', 'Ionogramme sanguin', 'biochimie', '{"id":"exam-012","code":"LAB012","name":"Ionogramme sanguin","category":"biochimie","parameters":["Sodium","Potassium","Chlore"],"sampleType":"Sang veineux","priceComptoir":15000,"priceSociete":13000,"priceExterne":18000,"urgentPrice":22000,"durationHours":2}'),
('exam-013', 'LAB013', 'TDR Paludisme', 'parasitologie', '{"id":"exam-013","code":"LAB013","name":"TDR Paludisme","category":"parasitologie","parameters":["TDR Paludisme"],"sampleType":"Sang capillaire","priceComptoir":5000,"priceSociete":4500,"priceExterne":6000,"urgentPrice":8000,"durationHours":1}'),
('exam-014', 'LAB014', 'Sérologie VIH / Syphilis', 'serologie', '{"id":"exam-014","code":"LAB014","name":"Sérologie VIH / Syphilis","category":"serologie","parameters":["VIH 1/2","TPHA/VDRL"],"sampleType":"Sang veineux","priceComptoir":12000,"priceSociete":10000,"priceExterne":15000,"urgentPrice":20000,"durationHours":2}');
