import type { AppState } from '../../store';
import type { AjoutFacturier, ClientType, NatureRemise } from '../../types';
import { sharedPersonnes, sharedSocietes, sharedTransactions, typeClientEffectif } from './sharedData';
import { billingFamilyResolver } from './billingFamilies';
import { natureRemiseEffective } from './utils/natureRemise';
import { buildSocieteFactureNumber, collectExistingFactureNumbers, generateUniqueSocieteCode, isAutoGeneratedCode } from '../../utils/factureNumber';

export interface BillingItem { description: string; actCode?: string; quantity?: number; unitPrice?: number; amount: number }
export interface BillingDocument {
  id: string; sourceId: string; category: ClientType; companyId?: string; companyName?: string;
  number: string; date: string; client: string; dossier?: string;
  matricule?: string; subCompany?: string; consultationDate?: string;
  /** Individual receipt values from the original piece, not insurer settlements. */
  individualGross?: number; individualNet?: number;
  /** Nature de la réduction (brut − net) : ticket modérateur (défaut) ou vraie
   *  remise — résolue à la collecte (société + dérogation de l'assuré). */
  natureRemise?: NatureRemise;
  total: number; copay: number; payable: number; paid: number; rejected: number;
  items: BillingItem[];
}
export interface MonthlyScope { month: string; category: ClientType; companyId?: string }
export interface MonthlyInvoice extends MonthlyScope {
  id: string;
  /** Société : numéro officiel FA-MM/CODE/YY-NNN de la facture GLOBALE
   *  mensuelle (ex: FA-09/JIR/26-001) ; comptoir / externes : FM-YYYY-MM-NNNN. */
  number: string; sequence: number; issuedAt: string; issuedBy: string; issuedByName: string;
  recipient: string; documents: BillingDocument[];
  total: number; copay: number; payable: number; paid: number; rejected: number; remaining: number;
  /** Trace of missing-family metadata repairs/migrations; original amounts stay frozen. */
  familyMetadataRepairs?: { date: string; userId: string; entries: { documentId: string; itemIndex: number; family: string }[] }[];
  facility: { name: string; address: string; phone: string; email: string; nif: string; currency: string };
}
export const categoryLabels: Record<ClientType, string> = { societe: 'Sociétés', comptoir: 'Comptoir', externe: 'Externes' };
export function localBillingDate(value: string): string {
  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return value;
  const date = new Date(value);
  if (!Number.isFinite(date.getTime())) return '';
  return new Intl.DateTimeFormat('en-CA', { timeZone: 'Indian/Antananarivo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(date);
}
export function monthlyScopeId(scope: MonthlyScope): string {
  if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(scope.month)) throw new Error('Mois de facturation invalide.');
  if (!['societe', 'comptoir', 'externe'].includes(scope.category)) throw new Error('Catégorie de facturation invalide.');
  if (scope.category === 'societe' && !scope.companyId) throw new Error('Sélectionnez une société pour cette facture mensuelle.');
  return `mensuelle:${scope.month}:${scope.category}${scope.category === 'societe' ? `:${scope.companyId}` : ''}`;
}

/** Same accounting sources, separate customer categories; no insurer entries
 * are fabricated for counter/external receipts. Mirrored legacy sales are skipped. */
export function collectBillingDocuments(state: AppState): BillingDocument[] {
  const transactions = sharedTransactions(state);
  const resolveFamily = billingFamilyResolver(state);
  // Réduction (brut − net) : ticket modérateur par défaut, vraie remise si la
  // société ou l'assuré le déclare (résolu une fois par pièce).
  const societes = sharedSocietes(state);
  const personnes = sharedPersonnes(state);
  const natureDe = (societeId?: string, personneId?: string): NatureRemise =>
    natureRemiseEffective(
      societeId ? societes.find(s => s.id === societeId) : undefined,
      personneId ? personnes.find(p => p.id === personneId) : undefined,
    );
  /** Ajouts du facturier (ventes omises / ordonnances externes) superposés aux
   *  lignes Caisse d'une facture comptoir / externe — même mécanisme que les
   *  prescriptions sociétés, sans jamais modifier la pièce d'origine. */
  const ajoutsFacturier = (ajouts: AjoutFacturier[] | undefined): { items: BillingItem[]; brut: number; moderateur: number } => {
    const lignes = ajouts || [];
    return {
      items: lignes.map(a => ({
        description: a.libelle || a.code,
        actCode: resolveFamily({ articleId: a.articleId, articleName: a.libelle, familyCode: a.code }),
        quantity: a.quantity, unitPrice: a.prixUnitaire, amount: a.totalPrestation,
      })),
      brut: rounded(lignes.reduce((s, a) => s + a.totalPrestation, 0)),
      moderateur: rounded(lignes.reduce((s, a) => s + (a.ticketModerateur || 0), 0)),
    };
  };
  const docs: BillingDocument[] = transactions.prestations.map(p => ({
    id: p.id, sourceId: p.sourceInvoiceId || p.id, category: 'societe', companyId: p.societeId,
    companyName: state.companies.find(c => c.id === p.societeId)?.name || p.societeNom || 'Société',
    number: p.numeroFacture, date: localBillingDate(state.invoices.find(i => i.id === p.sourceInvoiceId)?.createdAt || p.date), client: p.nomAgent || state.patients.filter(c => c.id === p.personneId).map(c => `${c.lastName} ${c.firstName}`.trim())[0] || 'Assuré',
    dossier: state.patients.find(c => c.id === p.personneId)?.dossier,
    matricule: p.matricule || state.patients.find(c => c.id === p.personneId)?.matricule,
    subCompany: p.sousSociete,
    consultationDate: localBillingDate(state.consultations.find(c => c.id === state.invoices.find(i => i.id === p.sourceInvoiceId)?.consultationId)?.date || p.date),
    individualGross: p.totalPrestation,
    individualNet: state.invoices.find(i => i.id === p.sourceInvoiceId)?.patientCharge ?? p.montantARembourser ?? p.totalPrestation - p.participation,
    natureRemise: natureDe(p.societeId, p.personneId),
    total: p.totalPrestation, copay: p.participation, payable: p.montantARembourser ?? p.totalPrestation - p.participation,
    paid: p.totalPaye || 0, rejected: p.montantExclu || 0,
    items: p.lignes.map((l, index) => {
      const item = state.invoices.find(i => i.id === p.sourceInvoiceId)?.items[index];
      return { description: l.libelle || l.code, actCode: item ? resolveFamily({ articleCode: item.code, articleName: item.description, category: item.category }) : resolveFamily({ familyCode: l.code }),
        quantity: item?.quantity, unitPrice: item?.unitPrice, amount: l.totalPrestation };
    }),
  }));
  for (const invoice of state.invoices) {
    // Type EFFECTIF : une facture validée en crédit société pour un patient
    // société appartient à la facturation société (voir typeClientEffectif) —
    // elle ne doit pas ressortir ici en double dans l'onglet Comptoir & Externe.
    const category = typeClientEffectif(state, invoice);
    if (category === 'societe') continue;
    // Encaissement d'un TICKET MODÉRATEUR à la caisse : ce n'est pas une pièce à
    // facturer (la quote-part figure déjà comme participation sur la prestation
    // société, et les espèces appartiennent à la clôture de caisse).
    if (invoice.copayTicketModerateur) continue;
    const sale = state.ventes.find(v => v.legacyInvoiceId === invoice.id);
    if (sale?.status === 'annule') continue;
    const patient = state.patients.find(p => p.id === invoice.patientId);
    const ajouts = ajoutsFacturier(invoice.ajoutsFacturier);
    docs.push({ id: `caisse:${invoice.id}`, sourceId: invoice.id, category,
      number: invoice.numeroFacture || sale?.numeroFacture || invoice.id, date: localBillingDate(invoice.createdAt),
      client: invoice.clientName || (patient ? `${patient.lastName} ${patient.firstName}`.trim() : categoryLabels[category]), dossier: patient?.dossier,
      matricule: patient?.matricule,
      consultationDate: localBillingDate(state.consultations.find(c => c.id === invoice.consultationId)?.date || invoice.createdAt),
      individualGross: rounded(invoice.totalAmount + ajouts.brut), individualNet: rounded(invoice.patientCharge + (ajouts.brut - ajouts.moderateur)),
      natureRemise: natureDe(undefined, invoice.patientId),
      total: rounded(invoice.totalAmount + ajouts.brut), copay: ajouts.moderateur, payable: rounded(invoice.totalAmount + (ajouts.brut - ajouts.moderateur)),
      paid: invoice.status === 'paid' && !invoice.creditSociete ? invoice.patientCharge : 0, rejected: 0,
      items: [...invoice.items.map(i => ({ description: i.description, actCode: resolveFamily({ articleCode: i.code, articleName: i.description, category: i.category }), quantity: i.quantity, unitPrice: i.unitPrice, amount: i.amount })), ...ajouts.items],
    });
  }
  // Standalone native sales (including external sales), without counting a
  // migrated invoice a second time or resurrecting a deleted legacy invoice.
  for (const sale of state.ventes) {
    if (sale.legacyInvoiceId || state.invoices.some(i => i.id === sale.id) || sale.status === 'annule') continue;
    const category = sale.isExterne ? 'externe' : sale.clientType;
    const company = category === 'societe' ? state.companies.find(c => c.name.trim().toUpperCase() === (sale.company || '').trim().toUpperCase()) : undefined;
    if (category === 'societe' && !company) continue;
    const patient = state.patients.find(p => p.id === sale.patientId);
    const ajouts = ajoutsFacturier(sale.ajoutsFacturier);
    docs.push({ id: `vente:${sale.id}`, sourceId: sale.id, category, companyId: company?.id, companyName: company?.name,
      number: sale.numeroFacture, date: localBillingDate(sale.dateVente),
      client: sale.clientName || (patient ? `${patient.lastName} ${patient.firstName}`.trim() : categoryLabels[category]), dossier: patient?.dossier,
      matricule: patient?.matricule, subCompany: sale.subCompany,
      consultationDate: localBillingDate(state.consultations.find(c => c.id === sale.consultationId)?.date || sale.dateVente),
      individualGross: rounded(sale.subtotal + ajouts.brut), individualNet: rounded(sale.montantFacture + (ajouts.brut - ajouts.moderateur)),
      natureRemise: natureDe(company?.id, sale.patientId),
      total: rounded(sale.montantFacture + ajouts.brut), copay: ajouts.moderateur, payable: rounded(sale.montantFacture + (ajouts.brut - ajouts.moderateur)), paid: sale.montantPaye, rejected: 0,
      items: [...state.venteLines.filter(l => l.venteId === sale.id).map(l => ({ description: l.articleName, actCode: resolveFamily({ articleId: l.articleId, articleName: l.articleName, category: l.category }), quantity: l.quantity, unitPrice: l.unitPrice, amount: Math.round(l.quantity * l.unitPrice * (1 - l.discount / 100) * 100) / 100 })), ...ajouts.items],
    });
  }
  return docs.sort((a, b) => b.date.localeCompare(a.date) || a.id.localeCompare(b.id));
}
export function documentsForScope(documents: BillingDocument[], scope: MonthlyScope): BillingDocument[] {
  return documents.filter(d => d.category === scope.category && d.date.slice(0, 7) === scope.month && (scope.category !== 'societe' || d.companyId === scope.companyId));
}
export function monthlyGroups(documents: BillingDocument[]): MonthlyScope[] {
  const map = new Map<string, MonthlyScope>();
  for (const d of documents) {
    if (!/^\d{4}-(0[1-9]|1[0-2])-\d{2}$/.test(d.date) || (d.category === 'societe' && !d.companyId)) continue;
    const scope = { category: d.category, month: d.date.slice(0, 7), companyId: d.companyId };
    map.set(monthlyScopeId(scope), scope);
  }
  return [...map.values()].sort((a, b) => b.month.localeCompare(a.month) || monthlyScopeId(a).localeCompare(monthlyScopeId(b)));
}
const rounded = (value: number) => Math.round(value * 100) / 100;
export function billingTotals(documents: BillingDocument[]) {
  const sum = (key: 'total' | 'copay' | 'payable' | 'paid' | 'rejected') => rounded(documents.reduce((s, d) => s + d[key], 0));
  const payable = sum('payable'), paid = sum('paid'), rejected = sum('rejected');
  return { total: sum('total'), copay: sum('copay'), payable, paid, rejected, remaining: rounded(Math.max(0, payable - paid - rejected)) };
}
/**
 * Code (diminutif) de la société pour sa facture GLOBALE mensuelle : le code
 * enregistré dans la base commune est utilisé s'il est « propre » ; sinon un
 * diminutif unique est généré (même règle que `resolveSocieteFactureCode`).
 */
function societeCodePourNumero(state: AppState, companyId: string, nomSociete: string): string {
  const societes = sharedSocietes(state);
  const soc = societes.find(s => s.id === companyId);
  const nom = (soc?.nom || nomSociete || 'Société').trim();
  if (soc?.code && !isAutoGeneratedCode(soc.code)) return soc.code.trim().toUpperCase();
  const codes = [
    ...societes.map(s => s.code),
    ...societes.map(s => s.nom),
    ...(state.companies || []).map(c => c.name),
  ];
  return generateUniqueSocieteCode(nom, codes);
}

/**
 * Numéro de la FACTURE GLOBALE mensuelle société : FA-MM/CODE/YY-NNN
 * (ex: FA-09/JIR/26-001) — MÊME format et MÊME séquence mensuelle partagée que
 * les numéros de la vue « par facture » (`buildSocieteFactureNumber`).
 * `takenNumbers` = tous les numéros déjà émis (factures journalières,
 * prestations, factures mensuelles…) pour garantir l'unicité de la séquence.
 */
export function societeMonthlyInvoiceNumber(state: AppState, companyId: string, nomSociete: string, month: string, takenNumbers: string[] = collectExistingFactureNumbers(state)): string {
  const code = societeCodePourNumero(state, companyId, nomSociete);
  const parsed = new Date(`${month}-15T12:00:00`);
  return buildSocieteFactureNumber(takenNumbers, code, Number.isFinite(parsed.getTime()) ? parsed : new Date());
}

/** Called inside the database transaction. Stable scope ID + saved sequence
 * prevent double-clicks, reprints and concurrent tabs from issuing duplicates. */
export function createMonthlyInvoice(state: AppState, scope: MonthlyScope, existing: MonthlyInvoice[], now = new Date().toISOString()): MonthlyInvoice {
  const id = monthlyScopeId(scope);
  const saved = existing.find(i => i.id === id);
  if (saved) return saved;
  if (!state.currentUser || !['admin', 'billing'].includes(state.currentUser.role)) throw new Error('Connexion facturation requise.');
  const documents = documentsForScope(collectBillingDocuments(state), scope);
  if (!documents.length) throw new Error('Aucune facture pour ce mois et cette catégorie.');
  if (documents.some(d => d.items.some(i => !i.actCode?.trim()))) throw new Error('Famille obligatoire manquante sur une ligne. Vérifiez les familles avant émission.');
  if (documents.some(d => [d.total, d.copay, d.payable, d.paid, d.rejected, ...d.items.map(i => i.amount)].some(n => !Number.isFinite(n) || n < 0))) throw new Error('Un montant est invalide. Corrigez la pièce d’origine avant émission.');
  const sequence = Math.max(0, ...existing.filter(i => i.month === scope.month).map(i => i.sequence)) + 1;
  // Société : la facture GLOBALE mensuelle porte le numéro officiel
  // FA-MM/CODE/YY-NNN (ex: FA-09/JIR/26-001). Comptoir / externes : format
  // mensuel FM-YYYY-MM-NNNN (ce ne sont pas des factures société).
  const number = scope.category === 'societe'
    ? societeMonthlyInvoiceNumber(state, scope.companyId!, documents[0]?.companyName || 'Société', scope.month)
    : `FM-${scope.month}-${String(sequence).padStart(4, '0')}`;
  return structuredClone({ ...scope, id, sequence, number, documents, ...billingTotals(documents),
    issuedAt: now, issuedBy: state.currentUser.id, issuedByName: state.currentUser.name,
    recipient: scope.category === 'societe' ? documents[0].companyName || 'Société' : `Clients ${categoryLabels[scope.category]}`,
    facility: billingFacility(state),
  });
}

/**
 * MIGRATION idempotente : les factures GLOBALE mensuelle société émises dans
 * l'ancien format mensuel (FM-YYYY-MM-NNNN) sont renumérotées au format
 * officiel société FA-MM/CODE/YY-NNN (ex: FA-09/JIR/26-001). Les factures
 * mensuelles comptoir / externes conservent le format FM-. Retourne le nombre
 * de pièces renumérotées (0 = rien à faire).
 */
export function migrateMonthlyInvoiceNumbers(state: AppState): number {
  const invoices = state.monthlyInvoices || [];
  const targets = invoices.filter(i => i.category === 'societe' && /^FM-\d{4}-\d{2}-\d{4}$/i.test(i.number || ''));
  if (!targets.length) return 0;
  const taken = new Set(collectExistingFactureNumbers(state).map(n => n.toUpperCase()));
  // Ordre stable : mois, puis ordre d'émission (séquence, puis horodatage).
  const sorted = [...targets].sort((a, b) => a.month.localeCompare(b.month) || a.sequence - b.sequence || a.issuedAt.localeCompare(b.issuedAt));
  const remap = new Map<string, string>();
  for (const inv of sorted) {
    const nom = inv.recipient || inv.documents?.[0]?.companyName || 'Société';
    const numero = societeMonthlyInvoiceNumber(state, inv.companyId || '', nom, inv.month, [...taken]);
    remap.set(inv.id, numero);
    taken.add(numero.toUpperCase());
  }
  state.monthlyInvoices = invoices.map(inv => (remap.has(inv.id) ? { ...inv, number: remap.get(inv.id)! } : inv));
  return remap.size;
}

/** Accounting snapshots are immutable. Durable stored versions win over an
 * old tab's copy and are never removed by an ordinary application autosave. */
export function preserveMonthlyInvoices(stored: MonthlyInvoice[] = [], incoming: MonthlyInvoice[] = []): MonthlyInvoice[] {
  const map = new Map(incoming.map(i => [i.id, i]));
  stored.forEach(i => map.set(i.id, i));
  return [...map.values()];
}

export function billingFacility(state: AppState): MonthlyInvoice['facility'] {
  const ts = state.ticketSettings, header = ts.assuranceHeader;
  return { name: header?.etablissement ?? ts.facilityName, address: header?.adresse ?? ts.address,
    phone: header?.telephone ?? ts.phone, email: header?.email ?? ts.email ?? '',
    nif: header?.nifStat ?? ts.nif, currency: ts.currency };
}

/* ====== VUE « PAR FACTURE » (regroupement par numéro de facture) ====== */

export interface BillingFactureGroup {
  number: string;
  category: ClientType;
  client: string;
  companyName?: string;
  subCompany?: string;
  dossier?: string;
  matricule?: string;
  dateMin: string;
  dateMax: string;
  documents: BillingDocument[];
  /** Nature de la réduction des pièces du groupe (remise si toutes le sont). */
  natureRemise?: NatureRemise;
  actes: number;
  total: number;
  copay: number;
  payable: number;
  paid: number;
  rejected: number;
  remaining: number;
  tauxRecouvrement: number;
  statut: 'Payé' | 'Partiellement payé' | 'En attente' | 'Rejeté';
}

/**
 * Regroupe les pièces par **numéro de facture** : une ligne par facture, comme
 * la vue « Prestations » du suivi assurance (N° facture, client/société,
 * période, actes, total brut, ticket modérateur, part à réclamer, perçu,
 * reste à réclamer, taux de recouvrement et statut).
 */
export function groupBillingDocumentsByFacture(documents: BillingDocument[]): BillingFactureGroup[] {
  const groups = new Map<string, BillingDocument[]>();
  for (const doc of documents) {
    const key = (doc.number || 'SANS_NUMERO').trim().toUpperCase();
    const bucket = groups.get(key);
    if (bucket) bucket.push(doc); else groups.set(key, [doc]);
  }
  return [...groups.values()].map(rows => {
    const dates = rows.map(d => d.date).filter(Boolean).sort();
    const total = rows.reduce((s, d) => s + d.total, 0);
    const copay = rows.reduce((s, d) => s + d.copay, 0);
    const payable = rows.reduce((s, d) => s + d.payable, 0);
    const paid = rows.reduce((s, d) => s + d.paid, 0);
    const rejected = rows.reduce((s, d) => s + d.rejected, 0);
    const remaining = Math.max(0, payable - paid - rejected);
    const premier = rows[0];
    const tauxRecouvrement = payable > 0 ? Math.round((paid / payable) * 100) : (paid > 0 ? 100 : 0);
    const statut: BillingFactureGroup['statut'] = rejected >= payable && payable > 0 && paid === 0
      ? 'Rejeté'
      : (paid >= payable && payable > 0) || (remaining <= 0 && paid > 0)
        ? 'Payé'
        : paid > 0 ? 'Partiellement payé' : 'En attente';
    return {
      number: premier.number || 'SANS_NUMERO', category: premier.category, client: premier.client,
      companyName: premier.companyName, subCompany: premier.subCompany,
      dossier: rows.find(d => d.dossier)?.dossier, matricule: rows.find(d => d.matricule)?.matricule,
      dateMin: dates[0] || '', dateMax: dates[dates.length - 1] || '',
      documents: rows.slice().sort((a, b) => a.date.localeCompare(b.date)),
      natureRemise: (rows.every(d => d.natureRemise === 'remise') ? 'remise' : 'ticket_moderateur') as NatureRemise,
      actes: rows.reduce((s, d) => s + d.items.length, 0),
      total, copay, payable, paid, rejected, remaining, tauxRecouvrement, statut,
    };
  }).sort((a, b) => b.dateMin.localeCompare(a.dateMin) || a.number.localeCompare(b.number));
}
